import PublicLayout from '@/components/landing/PublicLayout';

export default function PoliticaEnviosReembolsos() {
  return (
    <PublicLayout>
      <section className="py-20 md:py-28">
        <div className="max-w-3xl mx-auto px-6">
          <h1 className="text-3xl md:text-4xl font-bold text-white mb-3">Shipping & Refund Policy</h1>
          <p className="text-sm text-white/40 mb-10">Last updated: June 2026</p>
          <div className="space-y-8 text-sm text-white/60 leading-relaxed">
            <section>
              <h2 className="text-lg font-semibold text-white mb-3">1. Shipping process</h2>
              <p>JGS Trade Limited, operating as Logistics by JGS, manages international shipments from China to Argentina. The general shipping process includes:</p>
              <ul className="list-disc list-inside mt-2 space-y-1">
                <li><strong className="text-white/80">Pickup at origin:</strong> we coordinate the pickup of goods from the supplier or our warehouse in China.</li>
                <li><strong className="text-white/80">Consolidation:</strong> in the case of Import Pool, goods are consolidated with other shipments to optimize costs.</li>
                <li><strong className="text-white/80">Customs clearance:</strong> we manage all documentation and customs clearance at both origin and destination.</li>
                <li><strong className="text-white/80">International transport:</strong> goods travel by sea or air, depending on the chosen modality.</li>
                <li><strong className="text-white/80">Delivery at destination:</strong> once cleared, goods are delivered to the client's specified address in Argentina.</li>
              </ul>
            </section>
            <section>
              <h2 className="text-lg font-semibold text-white mb-3">2. Estimated shipping times</h2>
              <p>Estimated transit times vary by modality:</p>
              <ul className="list-disc list-inside mt-2 space-y-1">
                <li><strong className="text-white/80">Simplified Regime (courier):</strong> 15 to 30 business days from dispatch at origin.</li>
                <li><strong className="text-white/80">General Regime (sea freight):</strong> 45 to 75 business days from dispatch at origin.</li>
                <li><strong className="text-white/80">General Regime (air freight):</strong> 10 to 20 business days from dispatch at origin.</li>
                <li><strong className="text-white/80">Import Pool:</strong> variable depending on consolidation, generally 50 to 90 business days.</li>
              </ul>
              <p className="mt-2">These timeframes are estimates and may vary due to factors beyond JGS Trade Limited's control, including customs delays, weather conditions, port congestion, or force majeure. JGS Trade Limited does not guarantee exact delivery dates.</p>
            </section>
            <section>
              <h2 className="text-lg font-semibold text-white mb-3">3. Shipment tracking</h2>
              <p>All shipments include tracking through the Logistics by JGS platform. Clients can check the status of their operation in real time from their account.</p>
            </section>
            <section>
              <h2 className="text-lg font-semibold text-white mb-3">4. Refund conditions</h2>
              <p>JGS Trade Limited grants refunds in the following cases:</p>
              <ul className="list-disc list-inside mt-2 space-y-1">
                <li><strong className="text-white/80">Unconfirmed quote:</strong> if the client paid an advance for a quote that is ultimately not confirmed, 100% of the amount paid is refunded less administrative fees.</li>
                <li><strong className="text-white/80">Goods not received:</strong> if the goods do not arrive at destination within a reasonable timeframe and there is no force majeure justification, the client is entitled to a refund of the logistics service fee paid.</li>
                <li><strong className="text-white/80">Damaged goods:</strong> if the goods arrive damaged due to causes attributable to JGS logistics management, each case will be evaluated individually.</li>
                <li><strong className="text-white/80">Service error:</strong> if JGS Trade Limited incurs an error (e.g., dispatch to wrong address), the client will be compensated for the direct costs generated by the error.</li>
              </ul>
            </section>
            <section>
              <h2 className="text-lg font-semibold text-white mb-3">5. Cases where refunds do not apply</h2>
              <ul className="list-disc list-inside mt-2 space-y-1">
                <li>Transit delays within the communicated estimated ranges.</li>
                <li>Customs holds due to incomplete documentation provided by the client.</li>
                <li>Prohibited or restricted goods not declared by the client.</li>
                <li>Damage caused by inadequate packaging that is the supplier's or client's responsibility.</li>
                <li>Force majeure situations (natural disasters, conflicts, pandemics, government restrictions).</li>
              </ul>
            </section>
            <section>
              <h2 className="text-lg font-semibold text-white mb-3">6. How to request a refund</h2>
              <p>To request a refund, the client must:</p>
              <ol className="list-decimal list-inside mt-2 space-y-1">
                <li>Send an email to <a href="mailto:jgsourcingylogistics@gmail.com" className="text-primary hover:text-primary/80 transition-colors">jgsourcingylogistics@gmail.com</a> indicating the operation number and the reason.</li>
                <li>Attach supporting documentation (photos of damage, supplier communications, etc.), if applicable.</li>
                <li>The JGS team will evaluate the request within the following 10 (ten) business days.</li>
                <li>If approved, the refund will be processed within 15 (fifteen) business days following approval, using the same original payment method.</li>
              </ol>
            </section>
            <section>
              <h2 className="text-lg font-semibold text-white mb-3">7. Contact</h2>
              <p>For inquiries about shipments or refunds:</p>
              <ul className="mt-2 space-y-1">
                <li>Email: <a href="mailto:jgsourcingylogistics@gmail.com" className="text-primary hover:text-primary/80 transition-colors">jgsourcingylogistics@gmail.com</a></li>
                <li>Phone: <a href="tel:+541127855921" className="text-primary hover:text-primary/80 transition-colors">+54 11 2785 5921</a></li>
              </ul>
            </section>
          </div>
        </div>
      </section>
    </PublicLayout>
  );
}
